### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [CesarBalzer/telefones_uteis#2]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by CesarBalzer** [comment]
Olá @codehangen , o projeto encontra-se ativo ainda, sem manutenção no momento, mas obrigado pela colaboração.
Conte mais sobre suas idéias, o que você tem em mente para melhorias, novas implementações, explique mais sobre
